import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
from sprite import *

BUCKET = 'gag'

# ---------- THREE PIGEONS STARE AT THE CAMERA HOLE (gag) ----------
# Modular pigeon (body / head / neck / wing / legs). Each bird gets its own tint so the trio reads as three.
# Heads: 'side' (beak forward), 'diag' (beak up-forward, for the outer birds aiming at the centre hole),
# 'up' (beak straight up, for the bird under the hole). Blink variants are generated by swapping the eye.
BODY_W = 17
ROWS = dict(
    body="""
......PppppP.....
.....PppppppPP...
....PppppppppPPP.
....PpppppppPPPPP
....PppppppPPPPPP
....PpppppppPPPP.
.....PpppppppPP..
......PppppppP...
.......PPPPPP....
""",
    side="""
...PPPP..
..PppppP.
.PpwbpppP
nnPppppP.
..PPPPP..
""",
    diag="""
.n.......
nn.......
.nPPPP...
.PpwbppP.
.PpppppP.
..PPPPP..
""",
    up="""
...nn....
...nn....
..PPPP...
.PpwbpP..
.PpppPP..
.PppppP..
..PPPP...
""",
    neck="""
ppP
ppP
ppP
ppP
ppP
ppP
ppP
ppP
""",
    wing_mid="""
.PPPPPPP.
PPPPPPPPP
.PPPPPP..
""",
    wing_up="""
....PP..
...PPPP.
..PPPPP.
.PPPPPP.
PPPPPPP.
""",
    wing_down="""
PPPPPPP.
.PPPPPP.
..PPPPP.
...PPPP.
....PP..
""",
    legs="""
.n..n.
.n..n.
nn.nn.
""",
)
TINTS = [
    {},                                                        # classic grey
    {'p': (205, 165, 150), 'P': (140, 95, 85)},                # rosy brown
    {'p': (150, 175, 215), 'P': (90, 110, 160)},               # blue-grey
]
def _set(t):
    S = {k: sprite(v, t) for k, v in ROWS.items()}
    for h in ('side', 'diag', 'up'): S[h + '_blink'] = sprite(ROWS[h].replace('wb', 'pp'), t)
    return S
BIRDS = [_set(t) for t in TINTS]

def pigeon(im, c, S, x, y, face=1, pose='stand', head='side', hdy=0, blink=False):
    """S: sprite set. x,y: top-left of body. face 1 = beak left (as drawn), -1 = mirrored.
    pose: stand | fly_up | fly_down. head: side | diag | up. hdy: extra head y offset (bob / peck stretch)."""
    parts = [(S['body'], 0, 0)]
    if pose == 'stand':
        parts.append((S['wing_mid'], 5, 2)); parts.append((S['legs'], 5, 9))
    else:
        parts.append((S['wing_up'], 4, -4) if pose == 'fly_up' else (S['wing_down'], 4, 3))
    hs = S[head + ('_blink' if blink else '')]
    if head == 'side':
        parts.append((hs, -1, (-3 if pose == 'stand' else -2) + hdy))
    else:                                                # neck up: head sits over the front shoulder, neck fills the gap
        hy = -hs.height + 1 + hdy                        # head bottom row lands on y = hdy
        parts.append((hs, 0, hy))
        nh = 2 - hdy                                     # neck from head bottom down into the body's row 2
        if nh > 0: parts.append((S['neck'].crop((0, 0, 3, nh)), 4, hy + hs.height - 1))
    for spr, ox, oy in parts:
        if face < 0: spr = flip(spr); ox = BODY_W - spr.width - ox
        c.blit(im, spr, x + ox, y + oy)

def flap(i): return 'fly_up' if (i // 3) % 2 == 0 else 'fly_down'

def build():
    c = Clip('gag_pigeon_trio_01', 6.0)
    LY = H - 12
    # land_x, facing, fly-in start, fly-in frames [a,b), up-head kind, fly-out target, facing while leaving
    A = dict(lx=62,  face=-1, start=(-24, 2),     t_in=(1, 12),  up='diag', out=(-32, -20),   oface=1)
    B = dict(lx=84,  face=1,  start=(W + 6, 0),   t_in=(7, 18),  up='up',   out=(84, -26),    oface=1)
    C = dict(lx=106, face=1,  start=(W + 6, -10), t_in=(13, 24), up='diag', out=(W + 16, -20), oface=-1)
    birds = [A, B, C]
    T_OUT = 64
    for i in range(c.n):
        im = c.frame()
        for k, b in enumerate(birds):
            S = BIRDS[k]; a0, a1 = b['t_in']
            if i < a0: continue
            if i < a1:                                           # fly in, descend, settle
                t = ease((i - a0) / (a1 - a0 - 1))
                x = b['start'][0] + (b['lx'] - b['start'][0]) * t
                y = b['start'][1] + (LY - b['start'][1]) * t
                pigeon(im, c, S, x, y, b['face'], flap(i))
            elif i < T_OUT:
                face, head, hdy, blink, y = b['face'], 'side', 0, False, LY
                if i < a1 + 2: y = LY + 1; hdy = 1               # landing squash
                elif i < 32:                                     # idle: staggered bobs, one blink each
                    if (i + k * 3) % 9 == 0: hdy = 1
                    blink = (i + k * 4) % 13 == 5
                elif i < 44:                                     # SNAP: all three necks crane up at the hole, in unison
                    head, hdy = b['up'], -2; blink = 38 <= i < 40  # ...and one synchronised blink
                elif i < 46: head, hdy = b['up'], 0              # wind up: dip
                elif i < 49: head, hdy, y = b['up'], -5, LY - 1  # PECK up: neck stretches, tiny hop
                elif i < 51: head, hdy = b['up'], -3             # settle
                elif i < 54: head, hdy = b['up'], -2
                elif i < 58:                                     # look at each other: outer birds already face B
                    if k == 1: face = 1                          # B looks left at A...
                elif i < 62:
                    if k == 1: face = -1                         # ...then right at C
                    blink = (k != 1) and 59 <= i < 61            # A and C blink at each other
                else:                                            # crouch before take-off
                    y = LY + 1; hdy = 1
                    if k == 1: face = -1
                pigeon(im, c, S, b['lx'], y, face, 'stand', head, hdy, blink)
            else:                                                # fly off, three directions, together
                t = ease((i - T_OUT) / 7)
                x = b['lx'] + (b['out'][0] - b['lx']) * t
                y = LY + 1 + (b['out'][1] - LY - 1) * t
                pigeon(im, c, S, x, y, b['oface'], flap(i))
    return c
